#-----------------------------------------------------------------------
App       := GoodsApp
TARGET    := client
#DFLAGS    := all/O2/g
DFLAGS    := g
CONFIG    := 
STRIP_FLAG:= N
J2CPP_FLAG:= 
LOCAL_SRC += $(wildcard *.cpp)

INCLUDE   += 

LIB       += 

USER_H    +=
USER_OBJ  +=
#-----------------------------------------------------------------------
#include /home/tarsproto/GoodsApp/GoodsServer/GoodsTars.tars
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
