#-----------------------------------------------------------------------

App       := 
TARGET    := test
#DFLAGS    := all/O2/g
DFLAGS    := g
CONFIG    := lib
STRIP_FLAG:= N
J2CPP_FLAG:= 
LOCAL_SRC += $(wildcard *.cpp *.c )

INCLUDE   += -I./

LIB       += 
USER_H    +=
USER_OBJ  +=
#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
